# Generated by Django 6.0.1 on 2026-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
